#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compare AGENTS.md directory structure with actual files."""

import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ISSUE_BODY_FILE = os.path.join(REPO_ROOT, ".github", "issue_body.md")
ENGLISH_MIRROR_DIRS = ("docs/en/config", "docs/en/dev", "docs/en/providers")


def scan_files(directory, extensions):
    # type: (str, tuple) -> set
    """Scan directory for files with given extensions."""
    # Files to exclude from directory structure tracking
    exclude_files = {"docs/esa-deploy.md", "docs/esa.js", "docs/llms.txt", "docs/package.json"}

    result = set()
    base = os.path.join(REPO_ROOT, directory)
    if not os.path.isdir(base):
        return result
    for root, dirs, files in os.walk(base):
        dirs[:] = [d for d in dirs if not d.startswith(".") and d != "__pycache__"]
        for f in files:
            if not f.startswith(".") and f.endswith(extensions):
                rel_path = os.path.relpath(os.path.join(root, f), REPO_ROOT).replace(os.sep, "/")
                if rel_path not in exclude_files:
                    result.add(rel_path)
    return result


def parse_agents_md():
    # type: () -> tuple
    """Extract file paths from AGENTS.md directory structure (Tab-indented)."""
    agents_file = os.path.join(REPO_ROOT, "AGENTS.md")
    if not os.path.exists(agents_file):
        print("Error: AGENTS.md not found")
        sys.exit(1)

    with open(agents_file, "r", encoding="utf-8") as f:
        content = f.read()

    match = re.search(r"### Directory Structure.*?```text\s*\n(.*?)```\s*", content, re.DOTALL)
    if not match:
        return set(), set()

    files = set()
    directories = set()
    stack = []  # type: list
    for line in match.group(1).split("\n"):
        if not line.strip():
            continue
        depth = len(line) - len(line.lstrip("\t"))
        name = line.lstrip("\t").split(":")[0].strip()
        if not name or "*" in name or name == "...":
            continue

        stack = stack[:depth]
        if name.endswith("/"):
            stack.append(name.rstrip("/"))
            path = "/".join(stack)
            if path.startswith(("ddns/", "docs/", "schema/")):
                directories.add(path)
        else:
            path = "/".join(stack + [name])
            if path.startswith(("ddns/", "docs/", "schema/")) and not path.endswith(
                (".png", ".svg", ".jpg", ".gif", ".ico")
            ):
                files.add(path)
    return files, directories


def is_documented_english_mirror(path, actual, documented_dirs):
    # type: (str, set, set) -> bool
    """Check whether an English doc mirrors a documented Chinese source file."""
    for directory in ENGLISH_MIRROR_DIRS:
        if directory not in documented_dirs:
            continue
        prefix = directory + "/"
        if path.startswith(prefix):
            zh_path = path.replace("docs/en/", "docs/", 1)
            return zh_path in actual
    return False


def main():
    # type: () -> None
    actual = scan_files("ddns", (".py")) | scan_files("docs", (".md",)) | scan_files("schema", (".json",))
    documented, documented_dirs = parse_agents_md()
    actual = {f for f in actual if not is_documented_english_mirror(f, actual, documented_dirs)}

    added, deleted = sorted(actual - documented), sorted(documented - actual)

    # Check if any changes are in docs/ directory
    docs_changes = any(f.startswith("docs/") for f in added + deleted)

    # Remove old issue body file if exists
    if os.path.exists(ISSUE_BODY_FILE):
        os.remove(ISSUE_BODY_FILE)

    if not added and not deleted:
        print("No changes detected")
        sys.exit(0)

    # Build and write issue body
    lines = ["AGENTS.md directory structure is out of sync.\n"]
    if added:
        lines.append("## New Files\n")
        lines.extend("- `%s`" % f for f in added)
        lines.append("")
    if deleted:
        lines.append("## Missing Files\n")
        lines.extend("- `%s`" % f for f in deleted)
        lines.append("")
    lines.append("## Required Updates\n1. Update directory structure\n2. Update version/date")
    if docs_changes:
        lines.append("3. Update docs/llms.txt")
    lines.append("\n---\n*Auto-generated by update-agents workflow.*")

    with open(ISSUE_BODY_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("Changes detected: %d new, %d missing" % (len(added), len(deleted)))


if __name__ == "__main__":
    main()
