language: python
python:
  - "2.7"
  - "3.7"

dist: xenial

branches:
  only: 
    - master

os: 
  - linux
#   - osx

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PYINSTALLER='pyinstaller==3.6';else export PYINSTALLER=pyinstaller;fi

# command to install dependencies 
install:
  - pip install ${PYINSTALLER}

# command to run tests
script:
  - sed -i -e "s/\${BUILD_SOURCEBRANCHNAME}/${TRAVIS_BRANCH}/" -e "s/\${BUILD_DATE}/$(date --iso-8601=seconds)/" run.py
  - cp /etc/ssl/certs/ca-certificates.crt cert.pem
  - export SSL_CERT_FILE=${PWD}/cert.pem
  - pyinstaller --onefile --noconfirm --clean ./.build/ddns.spec
  - ./dist/ddns || test -e "config.json"

git:
  depth: 2

deploy:
  - provider: releases
    token: "${GH_TOKEN}"
    cleanup: false
    file:
      - "dist/ddns"
    on:
      tags: true
      branch: master
      python: '3.7'
  - provider: pypi
    username: newfuture-bot
    password: "${PYPI_PWD}"
    cleanup: false
    distributions: "sdist bdist_wheel" # Your distributions here
    on:
      tags: true
      branch: master
      python: '3.7'
