main: run.py
onefile: true
standalone: true
output-dir: ./dist
remove-output: true
assume-yes-for-downloads: true

include-modules:
  - dns.dnspod
  - dns.alidns
  - dns.dnspod_com
  - dns.dnscom
  - dns.cloudflare
  - dns.he
  - dns.huaweidns
  - dns.callback

macos-app-name: "DDNS"
product-name: "DDNS"
file-description: "DDNS Client 自动更新域名解析到本机IP"
company-name: "New Future"
copyright: "© 2016-2025"
windows-icon-from-ico: favor.ico
linux-icon: .build/icon.png
macos-app-icon: .build/icon.png
windows-console-mode: attach

output-name: "ddns"