# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-build

on:
  push:
    branches: ["test-build", "master"]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:

  nuitka:
    runs-on:  ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4


      # Prepare build version and cert
      - name: Replace build version
        run: sed -i.tmp -e "s#\${BUILD_VERSION}#${{ github.ref_name }}#" -e "s/\${BUILD_DATE}/$(date --iso-8601=seconds)/" run.py && rm run.py.tmp
        shell: bash
        
        # https://github.com/Nuitka/Nuitka/issues/2723#issuecomment-1960831891 
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: docker.io/centos:8
            options: -v ${{ github.workspace }}:/DDNS
            run: |
                cd /etc/yum.repos.d/ && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
                dnf config-manager --add-repo http://download.opensuse.org/repositories/home:/kayhayen/CentOS_8/home:kayhayen.repo
                dnf install -y epel-release \
                && dnf repolist \
                && dnf install -y gcc strace patchelf ccache gdb make python3-devel python3-zstandard python3-ordered-set
                dnf install -y nuitka     
                cd /DDNS &&  python3 .build/remove_python2.py && .build/nuitka.cmd

      - run: ./dist/ddns || test -e config.json
      - run: ./dist/ddns -h

      # Upload build result
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ddns-${{ runner.os }}
          if-no-files-found: error
          path: |
            dist/*.exe
            dist/*.bin
            dist/*.app
            dist/ddns