# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-build

on:
  push:
    branches: ["test-build", "master"]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:

  nuitka:
    runs-on:  ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4


      # Prepare build version and cert
      - name: Replace build version
        run: sed -i.tmp -e "s#\${BUILD_VERSION}#${{ github.ref_name }}#" -e "s/\${BUILD_DATE}/$(date --iso-8601=seconds)/" run.py && rm run.py.tmp
        shell: bash
        

      - name: run centos7
        run: |
            docker run -itd -v "$(pwd)":/tmp/DDNS --name centos7Instance --net="host" docker.io/centos:7 /bin/bash
            yum-config-manager --add-repo http://download.opensuse.org/repositories/home:/kayhayen/CentOS_7/home:kayhayen.repo
            sudo yum -y install swig gcc gcc-c++ kernel-devel nuitka python3
            python3 .build/remove_python2.py
            .build/nuitka.cmd



      - run: ./dist/ddns || test -e config.json
      - run: ./dist/ddns -h

      # Upload build result
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ddns-${{ runner.os }}
          if-no-files-found: error
          path: |
            dist/*.exe
            dist/*.bin
            dist/*.app
            dist/ddns