# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: publish python

on:
    push:
        branches:
            - master
        tags:
            - v*
            - V*
permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.x
              uses: actions/setup-python@v3
              with:
                  python-version: "3.x"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build package
              run: python -m build --sdist --wheel --outdir dist/
            # - name: Publish
            #   uses: pypa/gh-action-pypi-publish@v1
            #   with:
            #     user: __token__
            #     password: ${{ secrets.PYPI_API_TOKEN }}
            #     print_hash: true
            - name: Publish distribution 📦 to Test PyPI
              uses: pypa/gh-action-pypi-publish@v1
              with:
                  password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                  repository_url: https://test.pypi.org/legacy/
                  print_hash: true
